package biometrickeystroke;

import java.util.ArrayList;
import java.util.HashMap;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Monte
 */
public class BMAuth extends javax.swing.JFrame {
    ArrayList<Integer[]> storePress;
    ArrayList<Integer[]> storeDiff;
    Capture regListener;
    Capture logListener;
    Analize analyzer;
    ArrayList<String> password;
    HashMap<String, Integer> username;
    /**
     * Creates new form BMAuth    /**
     * Creates new form BMAuth
     */
    
    
    public BMAuth() {
        initComponents();
        regListener = new Capture();
        logListener = new Capture();
        storePress = new ArrayList();
        storeDiff = new ArrayList();
        password = new ArrayList();
        username = new HashMap();
        pwdReg.addKeyListener(regListener);
        pwdLog.addKeyListener(logListener);
        analyzer = new Analize();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        userReg = new javax.swing.JTextField();
        pwdReg = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regRE = new javax.swing.JButton();
        regNotify = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userLog = new javax.swing.JTextField();
        pwdLog = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logBtn = new javax.swing.JButton();
        logRE = new javax.swing.JButton();
        logNotify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 198, 30));

        userReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRegActionPerformed(evt);
            }
        });

        pwdReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdRegActionPerformed(evt);
            }
        });

        registerBtn.setText("Sign Up");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        regRE.setText("Re-Enter Password");
        regRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regREActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regRE)
                    .addComponent(jLabel1)
                    .addComponent(userReg, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(pwdReg, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn))
                .addContainerGap(189, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(regNotify)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(registerBtn)
                .addGap(18, 18, 18)
                .addComponent(regRE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(regNotify)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sign Up", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 203, 5));

        userLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLogActionPerformed(evt);
            }
        });

        pwdLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdLogActionPerformed(evt);
            }
        });

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        logBtn.setText("Sign In");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });

        logRE.setText("Re-Enter Password");
        logRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logREActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(logRE)
                    .addComponent(logBtn)
                    .addComponent(jLabel4)
                    .addComponent(userLog, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(pwdLog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(logNotify)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(logBtn)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logRE)
                    .addComponent(logNotify))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sign In", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        if (!pwdReg.getText().isEmpty() && !userReg.getText().isEmpty() && !regListener.getPressedKeys().contains("Backspace")) {
            username.put(userReg.getText(), username.size());
            password.add(pwdReg.getText());
            storePress.add(regListener.getPressedDiff());
            storeDiff.add(regListener.getDiff());
            regListener.keyPressDetail();
            regListener.clear();
            
            regNotify.setText("User " + userReg.getText()+ " is Signed Up");
            userReg.setText("");
            pwdReg.setText("");
        } else {
            regListener.clear();
            pwdReg.setText("");
            regNotify.setText("Please re-enter user details");
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        if (username.containsKey(userLog.getText())) {
            int i = username.get(userLog.getText());
            if(password.contains(pwdLog.getText())) {
                if(i == analyzer.analyzed(logListener.getPressedDiff(), logListener.getDiff(), storePress, storeDiff) - 1) {
                    logListener.clear();
                    
                    logNotify.setText("User " + userLog.getText() + " is Signed In");
                    userLog.setText("");
                    pwdLog.setText("");
                } else {
                    logNotify.setText("Wrong Match!");
                    userLog.setText("");
                    pwdLog.setText("");
                }
            } else {
                logListener.clear();
                logNotify.setText("Enter the correct password");
                userLog.setText("");
                    pwdLog.setText("");
            }
        } else {
            logNotify.setText("Enter the correct username");
            userLog.setText("");
            pwdLog.setText("");
        }
        
    
    }//GEN-LAST:event_logBtnActionPerformed

    private void pwdLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdLogActionPerformed

    private void userRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userRegActionPerformed

    private void pwdRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdRegActionPerformed

    private void regREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regREActionPerformed
            regListener.clear();
            pwdReg.setText("");
            regNotify.setText("");
    }//GEN-LAST:event_regREActionPerformed

    private void logREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logREActionPerformed
            logListener.clear();
            pwdLog.setText("");
            logNotify.setText("");
    }//GEN-LAST:event_logREActionPerformed

    private void userLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMAuth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logBtn;
    private javax.swing.JLabel logNotify;
    private javax.swing.JButton logRE;
    private javax.swing.JTextField pwdLog;
    private javax.swing.JTextField pwdReg;
    private javax.swing.JLabel regNotify;
    private javax.swing.JButton regRE;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField userLog;
    private javax.swing.JTextField userReg;
    // End of variables declaration//GEN-END:variables
}
